# PLS regression with agroclimatic metrics

**Repeat the PLS_chill_force procedure for the ‘Roter Boskoop’ dataset. Include plots of daily chill and heat accumulation.**

```{r, echo = TRUE}


temps = read_tab("TMaxTMin1958-2019_patched.csv")
temps_hourly = stack_hourly_temps(temps,latitude=50.6)

kable(head(temps), caption = "Hourly Temperature Klein Altendorf")  %>%
  kable_styling("striped", position = "left",font_size = 8)%>%
  scroll_box(width = "100%")

```


```{r, echo=TRUE}
daychill =
  daily_chill(
    hourtemps = temps_hourly,
    running_mean = 1,
    models = list(
      Chilling_Hours = Chilling_Hours,
      Utah_Chill_Units = Utah_Model,
      Chill_Portions = Dynamic_Model,
      GDH = GDH
    )
  )
 
# write.csv(daychill[[2]],"daychill.csv")

daychill_= read.csv("daychill.csv")

kable(head(daychill_), caption = "Daychill Klein Altendorf")  %>%
  kable_styling("striped", position = "left",font_size = 8)%>%
  scroll_box(width = "100%")
```



```{r, echo=TRUE}
dc =
  make_daily_chill_plot2(daychill,
                         metrics = c("Chill_Portions"),
                         cumulative = FALSE,
                         startdate=300,enddate=30,focusyears=c(2008, 2009, 1996), metriclabels="Chill Portions")
```




```{r, echo = TRUE}

```


