# Heatmaps 

>
In the previos lecture the chill comparison 



```{r, echo = FALSE, warning=FALSE, message=FALSE}
library(tidyverse)
library(lubridate)
library(reshape2)
library(dplyr)
library(ggplot2)
library(colorRamps)
library(tibble)
```



```{r, echo = TRUE}

weather_fue <- read_delim("/Users/Phil/Documents/Auswertung_Manuel_Juli_22/temp_hum_pres08.08.22.csv")

mod_weather_fue <-
  weather_fue %>% filter("2022-07-01 00:00:00" < date) %>%
  filter("2022-08-01 00:00:00" > date) %>%
  select(temperature, period, type, date, sensor) %>%
  filter(period == 1, type == 0, sensor == 0)

# preprocessing 

# create column with date
mod_weather_fue[,"date_new"] = 
  as.POSIXct(mod_weather_fue$date, format ="%m/%d/%Y %H:%M:%S" )

# separate hours (time)
mod_weather_fue[, "hours"] =
  format(mod_weather_fue$date_new, format = "%H:%M:%S")

# pick only hours
mod_weather_fue[, "hours_only"] = 
  as.numeric(substr(mod_weather_fue$hours, 1, 2))

# delete first row (individual fix)
mod_weather_fue = mod_weather_fue[-c(1), ]


# pick day 
mod_weather_fue[, "Tag"] =
  as.numeric(substr(mod_weather_fue$date, 9, 10))


# set new col Index with NA 
mod_weather_fue[,"Index"] <- NA


m3 <- mod_weather_fue

m3[,"countfactor"] <- NA


m1 <-m3 %>%
  # convert state to factor and reverse order of levels
  mutate(Index=factor(Index, levels=rev(sort(unique(Index)))))%>%
  mutate(countfactor=cut(temperature, breaks=c(8, 10, 12, 14, 16, 18, 20, 22,
                                         24,26,28,30,32,34,36, max(temperature, na.rm=TRUE)),
                         labels=c("8-10", "10-12", "12-14", "14-16", "16-18", "18-20",
                                  "20-22","22-24","24-26","26-28","28-30",
                                  "30-32","32-34","34-36","36 >")))%>%
mutate(countfactor=factor(as.character(countfactor), levels=rev(levels(countfactor))))


colors <- c("#002565", "#00556E", "#007763",
            "#007F3A", "#00860D","#198C00","#519300","#8B9803","#9D7608","#9A520B","#98300D","#951010","#931231","#901551","#8B1A89")
textcol <- "grey40"


ggplot(m1, aes(x=hours_only , y=Tag, fill=countfactor ))+
  geom_tile(colour="white", size=0.3)+
  geom_text(aes(label=round(temperature, digits = 1)), size=2.3)+
  scale_fill_manual(values=rev(colors), na.value = "grey90")+
  guides(fill=guide_legend(title="Temperatur in [°C]"))+
  theme_grey(base_size=10)+
  labs(x = "Hour", y = "Day")+
  ggtitle("Hourly mean Temperatures in Juli 2022")+
  theme(legend.position="bottom", legend.direction="horizontal",
        legend.title=element_text(colour=textcol),
        legend.margin=margin(grid::unit(0, "cm")),
        legend.text=element_text(colour=textcol, size=7, face="bold"),
        legend.key.height=grid::unit(0.8, "cm"),
        legend.key.width=grid::unit(0.2, "cm"),
        axis.text.x=element_text(size=10, colour=textcol),
        axis.text.y=element_text(vjust=0.2, colour=textcol),
        axis.ticks=element_line(size=0.4),
        plot.background=element_blank(),
        panel.border=element_blank(),
        plot.margin=margin(0.7, 0.4, 0.1, 0.2, "cm"),
        plot.title=element_text(colour=textcol, hjust=0, size=14, face="bold")
  )+
  scale_x_continuous(breaks = seq(from = 0, to = 23, by = 6))+
  scale_y_continuous(breaks = seq(0,31,1))

```




